java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Cfg.js -o ../min/js/Cfg.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar ClusterBuilder.js -o ../min/js/ClusterBuilder.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar ClusterPoints.js -o ../min/js/ClusterPoints.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Const.js -o ../min/js/Const.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar GeoLocation.js -o ../min/js/GeoLocation.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar InfoText.js -o ../min/js/InfoText.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar InfoWin.js -o ../min/js/InfoWin.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Map.js -o ../min/js/Map.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar PainterCrimePoint.js -o ../min/js/PainterCrimePoint.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar PainterRegion.js -o ../min/js/PainterRegion.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar QuerySDE.js -o ../min/js/QuerySDE.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Statistic.js -o ../min/js/Statistic.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Tools.js -o ../min/js/Tools.js --charset utf-8
java -jar C:\Java\jdk1.7.0_67\lib\yuicompressor.jar Util.js -o ../min/js/Util.js --charset utf-8