define({
    root: {
        PNG32: "PNG 32 colors",
        PNG8: "PNG 8 colors",
        mailPeriod1: "Daily",
        mailPeriod2: "Once in two days",
        mailPeriod7: "Weekly",
        crimeHard0: "all",
        crimeHard1: "little gravity",
        crimeHard2: "average gravity",
        crimeHard3: "grave",
        crimeHard4: "gravest",
        crimeHard5: "crimes",
        crimeHard6: "offenses",
        crimeHardLaw: "according to articles",
        TimePeriod0: "Twenty-four hours",
        TimePeriod1: "Night/Morning: 00:00 - 08:00",
        TimePeriod2: "Day: 08:00 - 16:00",
        TimePeriod3: "Evening/Night: 16:00 - 00:00",
        area1911: "Akmola region",
        area1915: "Aktobe region",
        area1919: "Almaty region",
        area1923: "Atyrau region",
        area1927: "West-Kazakhstan  region",
        area1931: "Zhambyl region",
        area1935: "Karaganda region",
        area1939: "Kostanay region",
        area1943: "Kyzylorda region",
        area1947: "Mangistau region",
        area1951: "South-Kazakhstan region",
        area1955: "Pavlodar region",
        area1959: "North-Kazakhstan region",
        area1963: "East-Kazakhstan region",
        area1971: "Astana c.",
        area1972: "GVP",
        area1975: "Almaty c.",
        area1987: "21-C",
        area7070: "Transport regions",

        reg191110: "Kokshetau",
        reg191118: "Stepnogorsk",
        reg191132: "Akkol district",
        reg191134: "Arshaly district",
        reg191136: "Astrakhan district",
        reg191138: "Atbassar district",
        reg191140: "Bulandy district",
        reg191144: "Egindykol district",
        reg191145: "Enbekshilder district",
        reg191146: "Ereimentau district",
        reg191148: "Yessil district",
        reg191152: "Zhaksynsky district",
        reg191154: "Zharkainsky district",
        reg191156: "Zerenda district",
        reg191160: "Korgalzhinsky district",
        reg191164: "Sandyktau district",
        reg191166: "Tselinograd district",
        reg191168: "Shortandy district",
        reg191170: "Schuchinsk district",

        reg191510: "Area  subordinated to Aktobe",
        reg191532: "Alga district",
        reg191534: "Aiteke bi district",
        reg191536: "Baiganainsky district",
        reg191540: "Kargaly district",
        reg191542: "Kobda district",
        reg191546: "Morty district",
        reg191548: "Mugalzhar district",
        reg191552: "Oiylsky district",
        reg191556: "Temir district",
        reg191560: "Khromtau district",
        reg191564: "Shalkar district",
        reg191568: "Yrgyz district",

        reg191910: "Taldykorgan",
        reg191916: "Kapchagai",
        reg191926: "Tekeli",
        reg191932: "Aksu district",
        reg191934: "Alakol district",
        reg191936: "Balkash district",
        reg191940: "Enbekshikazakh district",
        reg191942: "Zhambyl district",
        reg191946: "Kerbulak district",
        reg191948: "Koksu district",
        reg191950: "Karatal district",
        reg191952: "Karassai district",
        reg191956: "Panfilov district",
        reg191958: "Raiymbek district",
        reg191960: "Sarkand district",
        reg191962: "Talgar district",
        reg191964: "Yeskeldi district",
        reg191966: "Uigur district",
        reg191968: "Ille district",

        reg192310: "Atyrau",
        reg192336: "Zhylyoi district",
        reg192340: "Indersky district",
        reg192342: "Issatai district",
        reg192346: "Kurmangazy district",
        reg192348: "Kyzylkoginsky district",
        reg192352: "Makat district",
        reg192356: "Makhambetsky district",

        reg192710: "Ural city administration",
        reg192732: "Akzhaik district",
        reg192736: "Burlin district",
        reg192740: "Zhanakalinsky district",
        reg192742: "Zhanibeksky district",
        reg192744: "Zelenovsky district",
        reg192748: "Kaztal district",
        reg192750: "Karatobe district",
        reg192754: "Bokeiordinsky",
        reg192758: "Syrymsky district",
        reg192760: "Taskalinsky district",
        reg192762: "Terekty district",
        reg192766: "Shyngyrlausky district",

        reg193110: "Taraz city",
        reg193111: "Central district",
        reg193112: "Zheleznodorozhny district",
        reg193136: "Baizak district",
        reg193140: "Zhambyl district",
        reg193142: "Zhualy district",
        reg193148: "Kordai district",
        reg193150: "Turar Ryskulov",
        reg193154: "Merke district",
        reg193156: "Moiynkum district",
        reg193160: "Sarysu district",
        reg193162: "Talas district",
        reg193166: "Shu district",
        reg193167: "Shu city",

        reg193510: "Karagandy city",
        reg193511: "District named after Kazybek bi of Karagandy city",
        reg193516: "Balkhash",
        reg193518: "Zhezkazgan",
        reg193520: "Karazhal",
        reg193521: "Priozersk",
        reg193522: "Saran",
        reg193523: "Satpayev",
        reg193524: "Temirtau",
        reg193528: "Shakhtinsk",
        reg193532: "Abai district",
        reg193536: "Aktogai district",
        reg193540: "Bukhar Zhyrau district",
        reg193544: "Zhana-arka district",
        reg193548: "Karkaraly district",
        reg193552: "Nura district",
        reg193556: "Osakarovka district",
        reg193560: "Ulytau district",
        reg193564: "Shet district",
        reg193570: "Oktyabr district of Karagandy city",

        reg193910: "Kostanai city administration",
        reg193911: "South district of Kostanai city",
        reg193912: "North district of Kostanai city",
        reg193916: "Arkalyk",
        reg193920: "Lissakovsk city administration",
        reg193924: "Rudny city administration",
        reg193932: "Altynsarin district",
        reg193934: "Amankeldi district",
        reg193936: "Auliyekol district",
        reg193940: "Denissov district",
        reg193942: "Zhangeldi district",
        reg193944: "Zhitikara district",
        reg193948: "Kamystinsky district",
        reg193950: "Karabalyk district",
        reg193952: "Karasu district",
        reg193954: "Kostanai district",
        reg193956: "Mendykari district",
        reg193958: "Naurzumsky district",
        reg193962: "Sarykol district",
        reg193964: "Taran district",
        reg193966: "Uzynkol district",
        reg193968: "Feodorovsky district",

        reg194310: "Kyzylorda",
        reg194319: "Baikonyr",
        reg194332: "Aral district",
        reg194336: "Zhalagash district",
        reg194340: "Zhanakorgan district",
        reg194344: "Kazaly district",
        reg194346: "Karmakshi district",
        reg194348: "Syrdarya district",
        reg194352: "Shieli district",

        reg194710: "Aktau",
        reg194718: "Zhanaozen city",
        reg194736: "Beineu district",
        reg194742: "Karakiyansky district",
        reg194746: "Mangistau district",
        reg194750: "Munaily district",
        reg194752: "Tupkaragan district",

        reg195110: "Enbek district of Shymkent city",
        reg195111: "Abai district of Shymkent city",
        reg195112: "Al-Farabi district of Shymkent city",
        reg195113: "Karatau district of Shymkent city",
        reg195116: "Arys",
        reg195120: "Kentau",
        reg195126: "Turkestan",
        reg195132: "Arys district",
        reg195136: "Baidibek district",
        reg195140: "Kazygurt district",
        reg195144: "Maktaharal district",
        reg195146: "Ordabassy district",
        reg195148: "Otyrar district",
        reg195152: "Sairam district",
        reg195154: "Saryagash district",
        reg195156: "Suzaksky",
        reg195158: "Tole bi district",
        reg195160: "Tulkubas district",
        reg195164: "Shardary district",

        reg195510: "Pavlodar",
        reg195511: "South district of Pavlodar city",
        reg195516: "Aksu",
        reg195522: "Ekibastuz",
        reg195532: "Aktogai district",
        reg195536: "Bayanaul district",
        reg195542: "Zhelezinsky district",
        reg195546: "Ertis district",
        reg195548: "Kashir district",
        reg195552: "Lebyazhinsky",
        reg195556: "Mai district",
        reg195560: "Pavlodar district",
        reg195564: "Uspenka district",
        reg195568: "Sharbakty district",

        reg195910: "Petropavlovsk",
        reg195911: "Petropavlovsk c. 1-ОP",
        reg195912: "Petropavlovsk c. 2-ОP",
        reg195932: "Aiyrtau district",
        reg195934: "Akzhar district",
        reg195936: "Magzhan Zhumabnayev district",
        reg195942: "Yessil district",
        reg195946: "Zhambayl district",
        reg195950: "Kyzylzhar district",
        reg195952: "Mamlyutka district",
        reg195956: "Shal Akyn district",
        reg195958: "Akkaiyn district",
        reg195960: "Taiynshy district",
        reg195962: "Timiryazev district",
        reg195964: "Ualikhanovsky district",
        reg195966: "Gabit Musrepov district",

        reg196310: "Ust-Kamenogorsk",
        reg196311: "Ulba district",
        reg196312: "Levoberezhny district",
        reg196318: "Ayagoz",
        reg196320: "Zyryanovsk",
        reg196322: "Kurchatov",
        reg196324: "Ridder",
        reg196327: "Prigorodny district",
        reg196328: "Semipalatinsk",
        reg196329: "Auezov district",
        reg196330: "Zaton district",
        reg196331: "Central district",
        reg196332: "Abai district",
        reg196334: "Ayagoz district",
        reg196336: "Beskaragai district",
        reg196338: "Borodulikha district",
        reg196340: "Glubokovsky district",
        reg196344: "Zharma district",
        reg196346: "Zaissan district",
        reg196348: "Zyriyanovsky district",
        reg196350: "Kokpekty district",
        reg196352: "Kurshimsky district",
        reg196354: "Katon-Karagai district",
        reg196358: "Tarbagatai district",
        reg196362: "Ulan district",
        reg196364: "Urzhar district",
        reg196368: "Shemonaikha district",

        reg197110: "Astana city",
        reg197111: "Almaty district",
        reg197113: "Saryarka district",
        reg197115: "Yessil district",

        reg197510: "Almaty city",
        reg197511: "Almaly district",
        reg197512: "Alatau district",
        reg197513: "Auezov district",
        reg197514: "Bostandyk district",
        reg197515: "Zhetyssu district",
        reg197517: "Medeu district",
        reg197519: "Turksib district",
        reg197541: "Nauryzbai district",

        li15f0990: "Murder",
        li15f1000: "The killing by a mother of her newborn child",
        li15f1010: "Murder, committed in the affective state",
        li15f1020: "Murder, committed upon use of excessive",
        li15f1030: "Murder, committed upon excess of measures, necessary for detention of a person, committed a crime",
        li15f1040: "Cause death by negligence",
        li15f1050: "Incitement to suicide",
        li15f1060: "Intentional infliction of grievous harm to health",
        li15f1070: "Intentional infliction of average-gravity harm to health",
        li15f1080: "Intentional infliction of non-grave harm to health",
        li15f1110: "Infliction of harm to the health in affective state",
        li15f1120: "Infliction of grievous harm to health upon use of excessive force in self-defense",
        li15f1130: "Infliction of grievous harm to health upon detention of a person, committed a crime",
        li15f1140: "Negligent infliction of harm to health",
        li15f1190: "Leaving in danger",
        li15f1200: "Rape",
        li15f1210: "Violent acts of sexual nature",
        li15f1460: "Torment",
        li15f1490: "Violation of inviolability of housing",
        li15f1870: "Petty stealing",
        li15f1880: "Theft",
        li15f1900: "Fraud",
        li15f1910: "Robbery",
        li15f1920: "Robbery with violence",
        li15f1923: "Theft of items, having special value",
        li15f2880: "Illegal production of weapons",
        li15f2910: "Theft or extortion of weapons, ammunition, explosive substances and explosive devices",
        li15f2920: "Violation of requirements of fire safety",
        li15f2930: "Hooliganism",
        li15f2940: "Vandalism",
        li15f2970: "Illegal manufacture, processing, purchase, storage, transportation for the purpose of sale",
        li15f3000: "Illegal cultivation of plants, containing narcotic substances, prohibited to cultivation",
        li15f3020: "Organization or maintaining the premises for use of drugs or psychotropic substances",
        li15f3070: "Organization of illegal gambling business",
        li15f3090: "Organization or keeping disorderly houses for prostitution and procuration",
        li15f3100: "Organization or maintaining the premises for intoxication with drugs or other means",
        li15f3140: "Desecration of the dead persons and places of their burial places",

        lif0960: "Murder (art.96)",
        lif0970: "The killing by a mother of her newborn child (art.97)",
        lif0980: "Murder, committed in the affective state (art.98)",
        lif0990: "Murder, committed upon use of excessive self-Defense (art.99)",
        lif1000: "Murder, committed upon excess of measures necessary for detention of a person, committed a crime (art.100)",
        lif1010: "Cause death by negligence (art.101)",
        lif1030: "Intentional infliction of grievous harm to health (art.103)",
        lif1040: "Intentional infliction of average-gravity harm to health (art.104)",
        lif1200: "Rape (art.120)",
        lif1210: "Violent acts of sexual nature (art.121)",
        lif1220: "Sexual relationship or other actions of sexual nature with person, not reached the age of sixteen (art.122)",
        lif1240: "Corruption of minors (art.124)",
        lif1250: "Kidnapping (art.125)",
        lif1310: "Involvement of a minor in the commission of criminal infractions (art.131)",
        lif1750: "Theft (art.175)",
        lif1770: "Fraud (art.177)",
        lif1780: "Robbery (art.178)",
        lif1790: "Robbery with violence (art.179)",
        lif1810: "Extortion (art.181)",
        lif1850: "Illegal occupation of automobile or other vehicle without a purpose of plunder (art.185)",
        lif1870: "Intentional destruction or damaging of another’s property (art.187)",
        lif2330: "Terrorism (art.233)",
        lif2331: "Propaganda of terrorism or public calls for commission of an act of terrorism (art.233-1)",
        lif2332: "Creation, management of terrorist group and participation in its activity (art.233-2)",
        lif2333: "Financing of extremism and terrorist activities (art.233-3)",
        lif2350: "Creation and management of an organized criminal group or criminal community (criminal organization), participation in a criminal community (art..235)",
        lif2370: "Banditry (art.237)",
        lif2420: "Knowingly false report about an act of terrorism (art.242)",
        lif2570: "Hooliganism (art. 257)",
        lif2580: "Vandalism (art.258)",
        lif2590: "Illegal manufacture, acquisition, storage, transportation, transfer or selling of narcotic drugs or psychotropic substances (art.259 )",
        lif2600: "Theft or extortion of narcotic drugs or psychotropic substances (art.260)",
        lif2610: "Declination to consumption of narcotic drugs and psychotropic substances (art.261)",
        lif2640: "Organization or maintenance of dens for consumption of narcotic drugs or psychotropic substances (art. 264)",
        lif2960: "Violation of traffic rules or transport vehicles operation by persons, driving transport vehicles (art.296)",
        lif3240: "Theft or damage of documents, stamps, seals (art.324)",
        lif3250: "Forgery, manufacture or sale of forged documents, stamps, seals, forms, state awards (art.325)",

        all15Li0000: "Fact of criminal disappearance is not proved",
        all15Li0010: "Fact of criminal disappearance is not proved",
        all15Li0990: "Murder",
        all15Li1000: "The killing by a mother of her newborn child",
        all15Li1010: "Murder, committed in the affective state",
        all15Li1020: "Murder, committed upon use of excessive",
        all15Li1030: "Murder, committed upon excess of measures, necessary for detention of a person, committed a crime",
        all15Li1040: "Cause death by negligence",
        all15Li1050: "Incitement to suicide",
        all15Li1060: "Intentional infliction of grievous harm to health",
        all15Li1070: "Intentional infliction of average-gravity harm to health",
        all15Li1080: "Intentional infliction of non-grave harm to health",
        all15Li1090: "Blows",
        all15Li1100: "Torment",
        all15Li1110: "Infliction of harm to the health in affective state",
        all15Li1120: "Infliction of grievous harm to health upon use of excessive force in self-defense",
        all15Li1130: "Infliction of grievous harm to health upon detention of a person, committed a crime",
        all15Li1140: "Negligent infliction of harm to health",
        all15Li1150: "Threat",
        all15Li1160: "Forcible removal or illegal removal of organs and tissues of person",
        all15Li1170: "Infection with venereal disease",
        all15Li1180: "Infection of human immunodeficiency virus (HIV/AIDS)",
        all15Li1190: "Leaving in danger",
        all15Li1200: "Rape",
        all15Li1210: "Violent acts of sexual nature",
        all15Li1220: "Sexual relationship or other actions of sexual nature with person, not reached the age of sixteen",
        all15Li1230: "Coercion to sexual relationship, pederasty, lesbian act or other actions of sexual nature",
        all15Li1240: "Corruption of minors",
        all15Li1250: "Kidnapping",
        all15Li1260: "Illegal imprisonment",
        all15Li1270: "Illegal placement in a mental hospital",
        all15Li1280: "Human trafficking",
        all15Li1290: "Human cloning",
        all15Li1300: "Slander",
        all15Li1310: "Insult",
        all15Li1320: "Involvement of a minor in the commission of criminal infractions",
        all15Li1330: "Involvement of a minor in commission of antisocial actions",
        all15Li1340: "Involvement of a minor in prostitution",
        all15Li1350: "Trafficking in minors",
        all15Li1360: "Substitution of child",
        all15Li1370: "Illegal activity on adoption",
        all15Li1380: "Disclosure of secret of adoption",
        all15Li1390: "Non-performance of obligations on payment of child maintenance, evasion of funds for maintenance of disabled parents, disabled husband (wife)",
        all15Li1400: "Non-performance of obligations on upbringing of a minor",
        all15Li1410: "Improper performance of obligations on ensuring the safety of life and health of children",
        all15Li1420: "Abuse of rights of trustee or guardian",
        all15Li1430: "Illegal export of minor person outside of the Republic of Kazakhstan",
        all15Li1440: "Involvement of minors in production of articles with erotic content",
        all15Li1450: "Violation of the equality of person and citizen",
        all15Li1460: "Torment",
        all15Li1470: "Violation of integrity of private life and the legislation of the Republic of Kazakhstan on personal data and their protection",
        all15Li1480: "Illegal violation of privacy of letters, telephone conversations, postal, telegraphic or other messages",
        all15Li1490: "Violation of inviolability of housing",
        all15Li1500: "Interfering with implementation of election rights or the work of election commissions",
        all15Li1510: "Falsification of election documents, documents of referendum or incorrect counting of votes",
        all15Li1520: "Violation of the labor legislation of the Republic of Kazakhstan",
        all15Li1530: "Violation of labor legislation of the Republic of Kazakhstan in relation of minor",
        all15Li1540: "Interfering with legal activity of employee representatives",
        all15Li1550: "Interfering with organization, holding of meeting, political meeting, demonstration, procession, picketing or participation in them",
        all15Li1560: "Violation of labour protection rules",
        all15Li1570: "Coercion to participation in a strike or refuse of participation in a strike",
        all15Li1580: "Interfering with legal professional activity of journalist",
        all15Li1590: "Illegal restriction of a right to access to information resources",
        all15Li1600: "Planning, preparation, unleashing or conduct of aggressive war",
        all15Li1610: "Propaganda or public call for unleashing of aggressive war",
        all15Li1620: "Production, acquisition or sale of weapons of mass destruction",
        all15Li1630: "Application of prohibited means and methods of conduct of war",
        all15Li1640: "Violation of Laws or customs of war",
        all15Li1650: "Criminal violations of standards of international humanitarian law during armed conflicts",
        all15Li1660: "Omission or giving of criminal order during armed conflict",
        all15Li1670: "Illegal use of signs, protected by international treaties",
        all15Li1680: "Genocide",
        all15Li1690: "Ecocide",
        all15Li1700: "Mercenary activities",
        all15Li1710: "Developing the bases (camps) of training of mercenaries",
        all15Li1720: "Participation in the foreign armed conflicts",
        all15Li1730: "Attack against persons or organization, using international protection",
        all15Li1740: "Institution of social, national, generic, racial, class or religious discord",
        all15Li1750: "Treason",
        all15Li1760: "Spying",
        all15Li1770: "Infringement on life of the First President of the Republic of Kazakhstan - Leader of the Nation",
        all15Li1780: "Infringement on life of the President of the Republic of Kazakhstan",
        all15Li1790: "Propaganda or public calls for seizure or retention of power, as well as seizure or retention of power or forcible change of constitutional order of the Republic of Kazakhstan",
        all15Li1800: "Separatist activities",
        all15Li1810: "Armed rebellion",
        all15Li1820: "Creation, management of extremist group or participation in its activity",
        all15Li1830: "Giving permission for publication the extremist materials in the mass media",
        all15Li1840: "Sabotage",
        all15Li1850: "Illegal collection, dissemination, disclosure of the state secrets",
        all15Li1860: "Loss of the carriers of details, containing the state secrets",
        all15Li1870: "Petty stealing",
        all15Li1880: "Theft",
        all15Li1890: "Appropriation or embezzlement of entrusted another’s property",
        all15Li1900: "Fraud",
        all15Li1910: "Robbery",
        all15Li1920: "Robbery with violence",
        all15Li1930: "Theft of items, having special value",
        all15Li1940: "Extortion",
        all15Li1950: "Infliction of property damage by false pretenses or abuse of trust",
        all15Li1960: "Acquisition or sale of property, certainly obtained by illegal means",
        all15Li1970: "Transportation, acquisition, realization, storage of oil and oil products, as well as oil refining without documents, confirming legality of their origin",
        all15Li1980: "Infringement of copyright and (or) related rights",
        all15Li1990: "Infringement of rights to invention, utility models, industrial designs, selection achievements or topologies of integrated microcircuits",
        all15Li2000: "Illegal occupation of automobile or other means of transport without intent of theft",
        all15Li2010: "Violation of proprietary rights to land",
        all15Li2020: "Intentional destruction or damaging of another’s property",
        all15Li2030: "Intentional destruction or damaging of items, having special value",
        all15Li2040: "Negligent destruction or damaging of another’s property",
        all15Li2050: "Illegal access to information in the information system or information and communication network",
        all15Li2060: "Illegal destruction or modification of information",
        all15Li2070: "Disfunction of work of information system or information and communication network",
        all15Li2080: "Misappropriation of information",
        all15Li2090: "Coercion to transmission of information",
        all15Li2100: "Creation, use or distribution of malicious computer programs and program products",
        all15Li2110: "Illegal distribution of electronic information resources of restricted access",
        all15Li2120: "Provision of services for allocation of internet resources, pursuing illegal purposes",
        all15Li2130: "Illegal change of identification code of subscriber device of cell communication, subscriber identification device, as well as creation, use, distribution of programs for change of identification code of subscriber device",
        all15Li2140: "Illegal enterprise, illegal banking activity",
        all15Li2150: "Pseudo-entrepreneurship",
        all15Li2160: "Commission of actions on invoicing without actual performance of works, rendering of services, shipment of goods",
        all15Li2170: "Creation and management of financial (investment) pyramid",
        all15Li2180: "Legalization (laundering) of money and (or) other property, received by criminal way",
        all15Li2190: "Illegal obtaining of credit or unauthorized use of budget credit",
        all15Li2200: "Unauthorized use of money, received from placement of bonds",
        all15Li2210: "Monopolistic activity",
        all15Li2220: "Illegal use of trademark",
        all15Li2230: "Illegal acquisition and disclosure of details, constituting commercial or banking secrecy",
        all15Li2240: "Violation of procedure of issuance of equity securities",
        all15Li2250: "Non-provision of information or presentation of knowingly false details by civil servant of issuer of securities",
        all15Li2260: "Adding of knowingly false details in the register of security holders",
        all15Li2270: "Presentation of knowingly false details by professional participants of market securities",
        all15Li2280: "Violation of rules of conducting of securities transactions",
        all15Li2290: "Manipulation on the securities market",
        all15Li2300: "Illegal actions in relation of insider information",
        all15Li2310: "Production, storage, transportation, or sale of counterfeit money or securities",
        all15Li2320: "Production or sale of counterfeit charge cards and other payment or calculation documents",
        all15Li2330: "Violation of procedure and rules of marking of sub-excise goods by excise marks and (or) accounting and control marks, counterfeit and use of excise mark and (or) accounting and control marks",
        all15Li2340: "Economic smuggling",
        all15Li2350: "Non-return of means from abroad in the national and foreign currency",
        all15Li2360: "Evasion from payment of customs payments and charges",
        all15Li2370: "Illegal action upon rehabilitation and bankruptcy",
        all15Li2380: "Premeditated bankruptcy",
        all15Li2390: "Premeditated bankruptcy",
        all15Li2400: "False bankruptcy",
        all15Li2410: "Violation of the legislation of the Republic of Kazakhstan on book records and financial accountability",
        all15Li2420: "Presentation of knowingly false details on banking operations",
        all15Li2430: "Illegal use of money of bank",
        all15Li2440: "Evasion of citizen of taxes and (or) other compulsory payments in the budget",
        all15Li2450: "Evasion of taxes and (or) other compulsory payments in a budget with organization",
        all15Li2460: "Illegal actions in relation of property, restricted in management on account of debts for tax taxpayer",
        all15Li2470: "Obtain illegal remuneration",
        all15Li2480: "Coercion to the settlement of transaction or to refusal of its settlement",
        all15Li2490: "Corporate raiding",
        all15Li2500: "Abuse of power",
        all15Li2510: "Abuse of powers by private notaries, appraisers, private officers of justice, mediators and auditors, working as part of the audit organization",
        all15Li2520: "Excess of powers by servants of private security service",
        all15Li2530: "Commercial bribery",
        all15Li2540: "Unconscientious attitude to the obligations",
        all15Li2550: "An act of terrorism",
        all15Li2560: "Propaganda of terrorism or public calls for commission of an act of terrorism",
        all15Li2570: "Creation, management of terrorist group and participation in its activity",
        all15Li2580: "Financing of terrorist or extremist activity and other aiding and abetting to the terrorism or extremism",
        all15Li2590: "Enlistment or preparation or armament of persons in order of organization of terrorist or extremist activity",
        all15Li2600: "Undergoing the terrorist or extremist training",
        all15Li2610: "Taking of hostage",
        all15Li2620: "Creation and management of organized group, criminal organization, as well as participation in them",
        all15Li2630: "criminal organization, as well as participation in them as well as participation in it",
        all15Li2640: "Creation and management of transnational organized group, transnational criminal organization, as well as participation in them",
        all15Li2650: "Creation and management of transnational criminal society, as well as participation in it",
        all15Li2660: "Financing activity of criminal group, as well as storage, division of property, development financing channels",
        all15Li2670: "Organization of illegal paramilitary forces",
        all15Li2680: "Banditry",
        all15Li2690: "An attack against building, construction, means of communication and communication or their capture",
        all15Li2700: "Theft, as well as seizure of aircraft or water vessel, railway vehicles",
        all15Li2710: "Piracy",
        all15Li2720: "Mass disorders",
        all15Li2730: "Knowingly false report about an act of terrorism",
        all15Li2740: "Dissemination of knowingly false information",
        all15Li2750: "Illegal export of technologies, scientific and technical information and services, used upon creation of weapons of mass destruction, arms and military equipment",
        all15Li2760: "Violation of rules of safety on the objects of the atomic energy uses",
        all15Li2770: "Violation of rules of safety upon conducting of mining or construction works",
        all15Li2780: "Poor-quality construction",
        all15Li2790: "Violation of rules and requirements of standards in the scope of architectural, town-planning and construction activity",
        all15Li2800: "Improper performance of expert works or engineering services",
        all15Li2810: "Violation of rules of safety on the explosive objects",
        all15Li2820: "Violation of rules of safety upon carrying out of space activity",
        all15Li2830: "Illegal handling with radioactive substances, radioactive wastes, nuclear materials",
        all15Li2840: "Theft or extortion of radioactive substances, radioactive wastes, nuclear materials",
        all15Li2850: "Violation of rules of handling with radioactive substances, radioactive wastes, nuclear materials",
        all15Li2860: "Smuggling of withdrawn from handling of items or items, handling of which is restricted",
        all15Li2870: "Illegal acquisition, transfer, sale, storage, transportation or bearing of weapons, ammunition, explosive substance and explosive devices",
        all15Li2880: "Illegal production of weapons",
        all15Li2890: "Negligent keeping of fire weapons",
        all15Li2900: "Improper execution of obligations on security of weapons, ammunition, explosive substances or explosive devices",
        all15Li2910: "Theft or extortion of weapons, ammunition, explosive substances and explosive devices",
        all15Li2920: "Violation of requirements of fire safety",
        all15Li2930: "Hooliganism",
        all15Li2940: "Vandalism",
        all15Li2950: "Illegal performance of archeological works",
        all15Li2960: "Illegal handling with narcotic drugs, psychotropic substances, their analogues, precursors with no intent of sale",
        all15Li2970: "Illegal production, processing, acquisition, storage, transportation in order to sale, transfer or sale of narcotic drugs, psychotropic substances, their analogues",
        all15Li2980: "Theft or extortion of narcotic drugs, psychotropic substances, their analogues",
        all15Li2990: "Habitual use of narcotic drugs, psychotropic substances, their analogues",
        all15Li3000: "Illegal cultivation of plants, containing narcotic substances, prohibited to cultivation",
        all15Li3010: "Illegal trafficking poisonous substance, as wellIllegal trafficking poisonous substance, as well processing of narcotic drugs, psychotropic or poisonous substances",
        all15Li3020: "Organization or keeping disorderly houses for consumption of narcotic substances, psychotropic substances, their analogues and provision of premises for the same purposes",
        all15Li3030: "Violation of rules of handling with narcotic drugs, psychotropic or poisonous substances",
        all15Li3040: "Violation of sanitary rules or hygienic regulations",
        all15Li3050: "Information hiding on consequences, creating a danger for life or health of people",
        all15Li3060: "Release or sale of goods, execution of works or rendering of services, not meeting the requirements of safety",
        all15Li3070: "Organization of illegal gambling business",
        all15Li3080: "Involvement in prostitution",
        all15Li3090: "Organization or keeping disorderly houses for prostitution and procuration",
        all15Li3100: "Organization or keeping disorderly houses for stupefying with the use of medicinal or other products",
        all15Li3110: "Illegal distribution of pornographic materials or items",
        all15Li3120: "Production and turnover of materials or items with pornographic images of the minors or their involvement for participation in the entertainment events of pornographic nature",
        all15Li3130: "Illegal distribution of works, propagandizing cruelty and violence",
        all15Li3140: "Desecration of the dead persons and places of their burial places",
        all15Li3150: "Illegal removal of organs or body tissues of dead body",
        all15Li3160: "Cruelty to animals",
        all15Li3170: "Improper performance of professional obligations by medical or pharmaceutical employee",
        all15Li3180: "Violation of procedure of conducting of the clinical researches and use of the new methods and means of prevention, diagnosis, treatment and medical rehabilitation",
        all15Li3190: "Illegal performance of abortion",
        all15Li3200: "Failure to assist sick person",
        all15Li3210: "Disclosure of medical secret",
        all15Li3220: "Illegal medical and pharmaceutical activity and illegal issuance or forgery of prescriptions or other documents, granting the right to obtain the narcotic drugs or psychotropic substances",
        all15Li3230: "Handling with counterfeit drugs, medical products or medical equipment",
        all15Li3240: "Violation of environmental requirements to the economic or other activity",
        all15Li3250: "Violation of environmental requirements upon handling with environmentally potentially dangerous chemical or biological substances",
        all15Li3260: "Violation of environmental requirements upon handling with microbiological or other biological agents or toxins",
        all15Li3270: "Violation of veterinary rules or rules, established for disease control and plant pests",
        all15Li3280: "Pollution, clogging or depletion of waters",
        all15Li3290: "Pollution of the atmosphere",
        all15Li3300: "Pollution of the marine environment",
        all15Li3310: "Violation of the legislation on continental shelf of the Republic of Kazakhstan and exclusive economic zone of the Republic of Kazakhstan",
        all15Li3320: "the Republic of Kazakhstan",
        all15Li3330: "Violation of rules of protection and use of subsoil",
        all15Li3340: "Unauthorized subsoil use",
        all15Li3350: "Illegal extraction of fish resources, other aquatic animals or plants",
        all15Li3360: "Violation of rules of protection of fishery resources",
        all15Li3370: "Illegal hunting",
        all15Li3380: "Violation of rules of protection of animal life",
        all15Li3390: "Illegal handling with rare and endangered, as well prohibited to use the species of plants or animals, their parts or derivatives",
        all15Li3400: "Illegal cutting, destruction or damaging of trees and shrubs",
        all15Li3410: "Destruction or damaging of forests",
        all15Li3420: "Violation of the regime of specially protected natural sites",
        all15Li3430: "Failure to take measures on elimination of the consequences of environmental pollution",
        all15Li3440: "Violation of safety rules or operation of railway, air, sea or river transport",
        all15Li3450: "Violation of traffic rules or transport vehicles operation by persons, driving transport vehicles",
        all15Li3460: "Driving a transport vehicle by person, deprived of right of driving transport vehicles, being in the state of alcohol, drug, and (or) toxic intoxication, as well as transfer of control of the transport vehicle to such person or the admission to driving transport vehicle of such person",
        all15Li3470: "Leaving the place of road traffic accident",
        all15Li3480: "Substandard repair of transport vehicles or release for service with technical failures",
        all15Li3490: "Admission to drive the transport vehicle of a driver, not having a right to drive",
        all15Li3500: "Intentional disablement of transport vehicles or means of communication",
        all15Li3510: "Violation of rules, ensuring the safe operation of transport",
        all15Li3520: "Unauthorized unnecessarily train stop",
        all15Li3530: "Violation of current rules on transport",
        all15Li3540: "Violation of safety rules upon construction, operation or repair of main pipelines",
        all15Li3550: "Intentional damage or destruction of the pipeline",
        all15Li3560: "Careless damage or destruction of pipelines",
        all15Li3570: "Failure to render assistance to the suffering distress by captain of a ship",
        all15Li3580: "Control of air, sea, river, or a small vessel by person, being in a state of alcohol, drugs and (or) toxic intoxication, transfer of control to such person or admission to control of air, sea, river, or a small vessel of that person",
        all15Li3590: "to control of air, sea, river, or a small vessel of that person of person, not having the right to control",
        all15Li3600: "Violation of rules of international flights",
        all15Li3610: "Abuse of official authorities",
        all15Li3620: "Excess of powers or official authorities",
        all15Li3630: "Assignment of powers of civil servant",
        all15Li3640: "Illegal participation in the entrepreneurial activity",
        all15Li3650: "Interfering with legal entrepreneurial activity",
        all15Li3660: "Acceptance of a bribe",
        all15Li3670: "Giving bribe",
        all15Li3680: "Mediation in bribery",
        all15Li3690: "Forgery by an official",
        all15Li3700: "Inaction on service",
        all15Li3710: "Negligence",
        all15Li3720: "Desecration of state symbols",
        all15Li3730: "Public insult and other infringement on honour and dignity of the First President of the Republic of Kazakhstan - Leader of the Nation, desecration of images of the First President of the Republic of Kazakhstan – Leader of the Nation, interfering with legal activity of the First President of the Republic of Kazakhstan – Leader of the Nation",
        all15Li3740: "Violation of warranty of inviolability of the First President of the Republic of Kazakhstan – Leader of the Nation",
        all15Li3750: "Infringement on honour and dignity of the President of the Republic of Kazakhstan and interfering with his (her) activity",
        all15Li3760: "Infringement on honour and dignity of the deputy of the Parliament of the Republic of Kazakhstan and interfering with his (her) activity",
        all15Li3770: "Interfering with activity of the Constitutional Council of the Republic of Kazakhstan",
        all15Li3780: "Insult of representative of authority",
        all15Li3790: "Insubordination to representative of authority",
        all15Li3800: "Use of force in relation of representative of authority",
        all15Li3810: "Interfering with activity of prosecutor and nonfulfillment of his (her) legal requirements",
        all15Li3820: "Disclosure of details on safety measures, used in relation of civil servant, holding responsible state position",
        all15Li3830: "Acquisition or sale of official documents and state awards",
        all15Li3840: "Illegal suppression of documents, stealing, destruction, damaging or concealment of documents, stamps, seals",
        all15Li3850: "Forgery, production or sale of forged documents, stamps, seals, forms, state postage stamps, state awards",
        all15Li3860: "Forgery, destruction of vehicle identification number, sale of transport vehicle with certainly forged identification number",
        all15Li3870: "Evasion of military service",
        all15Li3880: "Evasion of call on mobilization",
        all15Li3890: "Arbitrariness",
        all15Li3900: "Unwarranted appropriation of title of representative of authority or civil servant, holding responsible state position",
        all15Li3910: "Illegal hoist of the State Flag of the Republic of Kazakhstan",
        all15Li3920: "Intentional illegal crossing of the State Border of the Republic of Kazakhstan",
        all15Li3930: "Nonperformance of decision on deportation",
        all15Li3940: "Organization of illegal migration",
        all15Li3950: "Repeated violation of rules of involvement and use f foreign labour in the Republic of Kazakhstan",
        all15Li3960: "Illegal change of the State border of the Republic of Kazakhstan.",
        all15Li3970: "Illegal use of emblems and signs of the Red Crescent, the Red Cross, Red Crystal",
        all15Li3980: "Violation of rules of protection of lines and installations of communication, as well as objects, subject to the state protection",
        all15Li3990: "Illegal processing, production, acquisition, sale or use of special technical means of surreptitious obtaining of information",
        all15Li4000: "Violation of the procedure of organization and holding of meetings, rallies, pickets, street processions and demonstrations",
        all15Li4010: "Management of prohibited industrial action, interfering with the work of organization in war time or conditions of emergency situations",
        all15Li4020: "The actions, provoking to continued participation in the industrial action, recognized by court as illegal",
        all15Li4030: "Illegal interference of members of public associations in the activity of the state bodies",
        all15Li4040: "Creation, management and participation in activity of illegal public and other associations",
        all15Li4050: "Organization and participation in activity of public or religious association or other organization after court decision on prohibition of their activity or liquidation in connection with carrying out by them the extremism or terrorism",
        all15Li4060: "Rendering assistance to the political parties and trade unions of the foreign state",
        all15Li4070: "Interfering with execution of justice and carrying out of prejudicial investigation",
        all15Li4080: "Infringement on life of person, executing the justice or prejudicial investigation",
        all15Li4090: "Threat or violent acts in connection with execution of justice or prejudicial investigation",
        all15Li4100: "Contempt of a court",
        all15Li4110: "Slander in relation of judge, jury member, prosecutor, person, executing prejudicial investigation, expert, bailiff, officer of justice",
        all15Li4120: "Involvement of certainly not guilty person to the criminal responsibility",
        all15Li4130: "Certainly illegal release from criminal responsibility",
        all15Li4140: "Certainly illegal detention, placement in custody or detention in custody",
        all15Li4150: "Compulsion of evidence",
        all15Li4160: "Falsification of evidences and operational and search materials",
        all15Li4170: "Provocation of commercial bribery or corruption",
        all15Li4180: "Imposition of certainly illegal sentence, decision or other judicial act",
        all15Li4190: "Knowingly false denunciation",
        all15Li4200: "Knowingly false testimony, conclusion of expert, specialist or erroneous translation",
        all15Li4210: "Failure of the witness or injured person to give evidence",
        all15Li4220: "Bribery or compulsion to give false evidences or evasion of giving evidences, false conclusion or to erroneous translation",
        all15Li4230: "Disclosure of details of pre-trial proceeding",
        all15Li4240: "Disclosure of details on safety measures, used in relation of persons, subject to the state protection",
        all15Li4250: "Illegal action in relation of property, subjected to inventory or arrest or subject to confiscation",
        all15Li4260: "Escape from the places of detention, arrest or custody",
        all15Li4270: "Evasion from serving a sentence in the form of imprisonment",
        all15Li4280: "Insubordination to the legal requirements of administration of criminal executive institution",
        all15Li4290: "A threat of the use of force in relation of officer of institution, providing isolation from society, or his (her) relatives, as well as convicted person or infringement on their health or life",
        all15Li4300: "Non-execution of sentence, court decision or other judicial act or executive document",
        all15Li4310: "Evasion from administrative supervision, established by court for persons, released from the places of detention",
        all15Li4320: "Concealment of crime",
        all15Li4330: "Concealment of criminal infraction",
        all15Li4340: "Failure to report crime",
        all15Li4350: "Interfering with legal activity of lawyers and other persons on protection of rights, freedoms and legal interests of person and citizen, as well as rendering of legal assistance to the individuals and legal entities",
        all15Li4360: "Interfering with the citizen to perform duties of jury member",
        all15Li4370: "Insubordination or other non-execution of order",
        all15Li4380: "Resistance to the head or compulsion him (her) to violation of official obligations",
        all15Li4390: "Violent actions in relation of the head",
        all15Li4400: "Violation of charter rules of relationship between military servants in the absence between them subordination relations",
        all15Li4410: "Unwarranted leaving of unit or place of service",
        all15Li4420: "Desertion",
        all15Li4430: "Evasion or refusal of serving military service",
        all15Li4440: "Evasion or refusal of serving military service",
        all15Li4450: "Violation of rules of protection of the State boundary of the Republic of Kazakhstan",
        all15Li4460: "Violation of charter rules of serving of guard (watch keeping) service",
        all15Li4470: "Violation of charter rules of serving of internal service or patrol in the garrison",
        all15Li4480: "Violation of rules of service of control service",
        all15Li4490: "Violation of rules of serving of service on protection of public order and ensuring of public security",
        all15Li4500: "Abuse of authority",
        all15Li4510: "Exceeding authority",
        all15Li4520: "Failure to use authority",
        all15Li4530: "Habitual negligence in office",
        all15Li4540: "Abandonment of a warship in distress",
        all15Li4550: "Surrender or leaving of means of warfare to the enemy",
        all15Li4560: "Voluntary surrender into captivity",
        all15Li4570: "Looting",
        all15Li4580: "Disclosure of security information of military nature or loss of carriers of security information of military nature",
        all15Li4590: "Intentional destruction or damaging of military property",
        all15Li4600: "Negligent destruction or damaging of military property",
        all15Li4610: "Loss of military property",
        all15Li4620: "Violation of rules of handling with weapons, as well as with materials and items, constituting a danger for others",
        all15Li4630: "Violation of rules of driving or operating of vehicles",
        all15Li4640: "Violation of flight rules or training to them",
        all15Li4650: "Violation of rules of ship navigation",
        all15Li4660: "Driving of vehicles, ship navigation, control of military aircraft by person in the state of alcoholic, narcotic or toxic intoxication, transmission driving or control or access to driving or control of military equipment of such person",
        allLi0960: "Murder",
        allLi0970: "The killing by a mother of her newborn child",
        allLi0980: "Murder, committed in the affective state",
        allLi0990: "Murder, committed upon use of excessive",
        allLi1000: "Murder, committed upon excess of measures, necessary for detention of a person, committed a crime",
        allLi1010: "Cause death by negligence",
        allLi1020: "Incitement to suicide",
        allLi1030: "Intentional infliction of grievous harm to health",
        allLi1040: "Intentional infliction of average-gravity harm to health",
        allLi1050: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of activation, see cl. 2)",
        allLi1060: "Excluded by the RK Law No. 10-III dated December  9, 2004",
        allLi1070: "Torment",
        allLi1080: "Infliction of harm to the health in affective state",
        allLi1090: "Infliction of grievous harm to health upon use of excessive force in self-defense",
        allLi1100: "Infliction of grievous harm to health upon detention of a person, committed a crime",
        allLi1110: "Negligent infliction of harm to health",
        allLi1120: "Threat",
        allLi1130: "Forcible removal or illegal removal of organs and tissues of person",
        allLi1140: "Improper performance of professional duties of medical staff and pharmaceutists",
        allLi1141: "Violation of the order of conducting clinical research and application of new methods and means of prevention, diagnosis, treatment and medical rehabilitation",
        allLi1150: "Infection with venereal disease",
        allLi1160: "Infection of human immunodeficiency virus (HIV/AIDS)",
        allLi1170: "Illegal performance of abortion",
        allLi1180: "Failure to assist sick person",
        allLi1190: "Leaving in danger",
        allLi1200: "Rape",
        allLi1210: "Violent acts of sexual nature",
        allLi1220: "Sexual relations and other sexual acts with a person under 16",
        allLi1230: "Coercion to sexual relationship, pederasty, lesbian act or other actions of sexual nature",
        allLi1240: "Corruption of minors",
        allLi1250: "Kidnapping",
        allLi1260: "Illegal imprisonment",
        allLi1270: "Illegal placement in a mental hospital",
        allLi1280: "Human trafficking",
        allLi1290: "Slander",
        allLi1300: "Insult",
        allLi1310: "Involvement of a minor in the commission of criminal infractions",
        allLi1320: "Involvement of a minor in commission of antisocial actions",
        allLi1321: "Involvement of a minor in prostitution",
        allLi1330: "Trafficking in minors",
        allLi1340: "Substitution of child",
        allLi1350: "Disclosure of secret of adoption",
        allLi1360: "Failure to fulfill obligations on payment of funds for the maintenance of children or disabled parents",
        allLi1370: "Non-performance of obligations on upbringing of a minor",
        allLi1380: "Improper performance of obligations on ensuring the safety of life and health of children",
        allLi1381: "Violation of labor legislation of the Republic of Kazakhstan in relation of minor",
        allLi1390: "Abuse of rights of trustee or guardian",
        allLi1400: "Evasion of a disabled husband (wife) maintenance",
        allLi1410: "Violation of citizens' equality",
        allLi1411: "Torment",
        allLi1420: "Violation of privacy and the Republic of Kazakhstan legislation on personal data and their protection",
        allLi1430: "Illegal violation of the secrecy of correspondence, telephone conversations, postal, telegraph or other messages",
        allLi1440: "Disclosure of medical secret",
        allLi1450: "Violation of inviolability of housing",
        allLi1460: "Interfering with implementation of election rights or the work of election commissions",
        allLi1470: "Falsification of election documents, documents of referendum or incorrect counting of votes",
        allLi1480: "Violation of the labor legislation of the Republic of Kazakhstan",
        allLi1490: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi1500: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi1501: "Interfering with legal activity of employee representatives",
        allLi1510: "Obstruction of holding meetings, rallies, demonstrations, marches, picketing or participation in them",
        allLi1520: "Violation of labour protection rules",
        allLi1530: "Coercion to participation in a strike or refuse of participation in a strike",
        allLi1540: "Excluded by the RK Law No. 10-III dated  December 9, 2004",
        allLi1550: "Interfering with legal professional activity of journalist",
        allLi1560: "Planning, preparation, unleashing or conduct of aggressive war",
        allLi1570: "Propaganda and public calls for aggressive war",
        allLi1580: "Manufacture or distribution of weapons of mass destruction",
        allLi1590: "Application of prohibited means and methods of conduct of war",
        allLi1600: "Genocide",
        allLi1610: "Ecocide",
        allLi1620: "Mercenary activities",
        allLi1630: "Assault on persons or organizations enjoying international protection",
        allLi1640: "Incitement of social, national, tribal, racial or religious hatred",
        allLi1650: "Treason",
        allLi1660: "Spying",
        allLi1661: "Infringement on life of the First President of the Republic of Kazakhstan - Leader of the Nation",
        allLi1670: "Infringement on life of the President of the Republic of Kazakhstan",
        allLi1680: "Violent capture of power or violent deduction of power or implementation by the representatives of a foreign state or foreign organization of powers within the competence of the authorized bodies and officials of the Republic of Kazakhstan",
        allLi1690: "Armed rebellion",
        allLi1700: "Calls for the violent overthrow or change the constitutional order or the violent disruption of the unity of the Republic of Kazakhstan",
        allLi1710: "Sabotage",
        allLi1720: "Illegal acquisition, disclosure, distribution of state secrets",
        allLi1730: "Loss of documents, objects containing the state secrets",
        allLi1740: "Evasion of call on mobilization",
        allLi1750: "Theft",
        allLi1760: "Appropriation or embezzlement of entrusted another’s property",
        allLi1770: "Fraud",
        allLi1771: "Creation and (or) management of financial activities (investment) pyramid",
        allLi1780: "Robbery",
        allLi1790: "Robbery with violence",
        allLi1800: "Theft of items, having special value",
        allLi1810: "Extortion",
        allLi1820: "Infliction of property damage by false pretenses or abuse of trust",
        allLi1830: "Acquisition or sale of property, certainly obtained by illegal means",
        allLi1831: "Transportation, acquisition, realization, storage of oil and oil products, as well as oil refining without documents, confirming legality of their origin",
        allLi1840: "Infringement of copyright and (or) related rights",
        allLi1841: "Violation of the rights to inventions, utility models, industrial designs, selection achievements or topologies of integrated circuits",
        allLi1850: "Illegal occupation of automobile or other means of transport without intent of theft",
        allLi1860: "Violation of proprietary rights to land",
        allLi1870: "Intentional destruction or damaging of another’s property",
        allLi1880: "Negligent destruction or damaging of another’s property",
        allLi1890: "Excluded",
        allLi1900: "Illegal enterprise",
        allLi1910: "Illegal Banking Activity",
        allLi1920: "Pseudo-entrepreneurship",
        allLi1921: "Making by the subject of a private of a business transaction  (transactions) with no intention to engage in entrepreneurial activity",
        allLi1930: "The legalization of money or other property acquired by criminal means",
        allLi1940: "Illegal acquisition and misuse of credit",
        allLi1941: "Unauthorized use of money, received from placement of bonds",
        allLi1950: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi1960: "Monopolistic activity",
        allLi1970: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi1980: "Knowingly false advertisement",
        allLi1990: "Illegal use of trademark",
        allLi2000: "Illegal acquisition and disclosure of details, constituting commercial or banking secrecy",
        allLi2010: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi2020: "Violation of the order of issue of securities",
        allLi2021: "Failure to submit information or submission of false information by an officer of the securities’ issuer",
        allLi2030: "Adding of knowingly false details in the register of security holders",
        allLi2040: "Presentation of knowingly false details by professional participants of market securities",
        allLi2050: "Violation of rules of conducting of securities transactions",
        allLi2051: "Loss of documents and information constituting the system registers of securities holders",
        allLi2060: "Manufacturing or selling of counterfeit money or securities",
        allLi2070: "Production or sale of counterfeit charge cards and other payment or calculation documents",
        allLi2080: "Violation of the procedure and the rules of marking excise goods with excise stamps and (or) the accounting and control brands, forgery and use of excise stamps and (or) the accounting and control stamps",
        allLi2090: "Economic smuggling",
        allLi2100: "Excluded by the RK Law No. 277-1 dated July 9, 1998",
        allLi2110: "Excluded by the RK Law No. 277-1 dated July 9, 1998",
        allLi2120: "Excluded by the RK Law No. 277-1 dated July 9, 1998",
        allLi2130: "Non-return of means from abroad in the national and foreign currency",
        allLi2140: "Evasion from payment of customs payments and charges",
        allLi2150: "Illegal action upon at bankruptcy",
        allLi2160: "Premeditated bankruptcy",
        allLi2161: "Premeditated bankruptcy",
        allLi2170: "False bankruptcy",
        allLi2180: "Violation of the legislation of the Republic of Kazakhstan on book records and financial accountability",
        allLi2190: "Presentation of knowingly false details on banking operations",
        allLi2200: "Illegal use of money of bank",
        allLi2210: "Evasion of citizen of taxes and (or) other compulsory payments in the budget",
        allLi2220: "Evasion of taxes and (or) other compulsory payments in a budget with organization",
        allLi2221: "Illegal acts concerning the property restricted for disposal at the expense of the taxpayer's tax debt",
        allLi2230: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi2240: "Obtain illegal remuneration",
        allLi2250: "Excluded by the RK Law No. 393-IV dated January 18, 2011 (procedure of enforcement see art. 2)",
        allLi2260: "Coercion to the settlement of transaction or to refusal of its settlement",
        allLi2261: "Corporate raiding",
        allLi2270: "Illegal access to computer information, creation, use and distribution of malicious computer programs to ECM.",
        allLi2271: "Unauthorized change of the identification code of the subscriber mobile device, subscriber device identification, as well as the creation, use and distribution of programs to change the identification code of the subscriber device.",
        allLi2280: "Abuse of power",
        allLi2290: "Abusing powers of private notaries, private bailiffs and auditors working in the composition of the audit organization",
        allLi2300: "Excess of powers by servants of private security service",
        allLi2310: "Commercial bribery",
        allLi2320: "Unconscientious attitude to the obligations",
        allLi2330: "Act of terrorism",
        allLi2331: "Promotion of terrorism or extremism or public incitement to commit a terrorist act.",
        allLi2332: "Creation, management of terrorist group and participation in its activity",
        allLi2333: "Financing of terrorist or extremist activities and other assistance to terrorism or extremism.",
        allLi2334: "Recruitment or training arms or persons in order to organize a terrorist or extremist activity.",
        allLi2340: "Taking of hostage",
        allLi2350: "Creation and management of an organized group for the purpose of committing one or more crimes, as well as participation in it",
        allLi2351: "Creation and management of a criminal community (criminal organization), as well as participation in it.",
        allLi2352: "Creation and management of transnational organized group for the purpose of committing one or more crimes, as well as participation in it.",
        allLi2353: "Creation and management of transnational criminal community (transnational criminal organization), as well as participation in it.",
        allLi2354: "Financing activity of organized group, a criminal association (criminal organization) or transnational organized group, transnational criminal community (transnational criminal organization) or a stable armed group (band), as well as the collection, storage, division of property, development financing channels",
        allLi2360: "Organization of illegal paramilitary forces",
        allLi2370: "Banditry",
        allLi2380: "Attacks against buildings, facilities, means of communication and communication",
        allLi2390: "Theft, as well as seizure of aircraft or water vessel, railway vehicles",
        allLi2400: "Piracy",
        allLi2410: "Mass disorders",
        allLi2420: "Knowingly false report about an act of terrorism",
        allLi2430: "Illegal export of technologies, scientific and technical information and services, used upon creation of weapons of mass destruction, arms and military equipment",
        allLi2440: "Violation of safety regulations at nuclear facilities",
        allLi2450: "Violation of rules of safety upon conducting of mining or construction works",
        allLi2451: "Poor-quality construction",
        allLi2460: "Violation of rules of safety on the explosive objects",
        allLi2461: "Violation of rules of safety upon carrying out of space activity",
        allLi2470: "Illegal handling of radioactive materials",
        allLi2480: "Stealing or Extortion of radioactive materials",
        allLi2490: "Violation of the rules for handling radioactive materials",
        allLi2500: "Smuggling of withdrawn from handling of items or items, handling of which is restricted",
        allLi2510: "Illegal acquisition, transfer, sale, storage, transportation or bearing of weapons, ammunition, explosive substance and explosive devices",
        allLi2520: "Illegal production of weapons",
        allLi2530: "Negligent keeping of fire weapons",
        allLi2540: "«Improper Execution of Obligations Associated with the Protection of Arms, Ammunitions, Explosives, or Explosion Devices",
        allLi2550: "Theft or extortion of weapons, ammunition, explosive substances and explosive devices",
        allLi2560: "«Violation of Fire Safety Rules",
        allLi2570: "Hooliganism",
        allLi2580: "Vandalism",
        allLi2590: "Illegal manufacture, processing, purchase, storage, transportation, transfer or sale of narcotic drugs or psychotropic substances",
        allLi2600: "Theft or extortion of narcotic drugs and psychotropic substances",
        allLi2610: "Inducement to use narcotic drugs or psychotropic substances",
        allLi2620: "Illegal cultivation of plants, containing narcotic substances, prohibited to cultivation",
        allLi2630: "Illegal trafficking of toxic substances, and materials, tools, or equipment, used for the manufacture or processing of narcotic drugs, psychotropic or toxic substances",
        allLi2640: "Organization or maintaining the premises for use of drugs or psychotropic substances, or the provision of facilities for the same purpose",
        allLi2650: "Violation of rules for handling of narcotic drugs, psychotropic or toxic substances",
        allLi2660: "Illegal medical and pharmaceutical activities and illegal issuance or forgery of prescriptions or other documents granting the right to receipt narcotic drugs or psychotropic substances",
        allLi2670: "Violation of Sanitary-Epidemiological Rules",
        allLi2680: "Information hiding on consequences, creating a danger for life or health of people",
        allLi2690: "Issue or sale of goods, and execution of works or services that do not meet the safety requirements",
        allLi2691: "Organization of illegal gambling business",
        allLi2700: "Involvement in prostitution",
        allLi2710: "Organization or keeping disorderly houses for prostitution and procuration",
        allLi2720: "Organization or maintaining the premises for intoxication with drugs or other means",
        allLi2730: "Illegal distribution of pornographic materials or items",
        allLi2731: "Manufacture and distribution of materials or objects with pornographic images of minors or their attraction to participate in entertainment pornographic events",
        allLi2740: "Illegal distribution of works, propagandizing cruelty and violence",
        allLi2750: "Desecration of the dead persons and places of their burial places",
        allLi2751: "Illegal removal of organs or body tissues of dead body",
        allLi2760: "Cruelty to animals",
        allLi2770: "Violation of ecological requirements to the economic and another activity",
        allLi2780: "Violation of ecological requirements during the production and use of potentially dangerous for ecology chemical, radioactive and biological substances",
        allLi2790: "Violation of safety rules during the handling of microbiological or other biological agents or toxins",
        allLi2800: "Violation of veterinary rules and the rules, which are established for the disease and plant pests’ control",
        allLi2810: "Pollution, clogging and depletion of waters",
        allLi2820: "Pollution of the atmosphere",
        allLi2830: "Pollution of the marine environment",
        allLi2840: "Violation of the legislation of continental shelf of the Republic of Kazakhstan and of exclusive economic zone of the Republic of Kazakhstan",
        allLi2850: "the Republic of Kazakhstan",
        allLi2860: "Violation of rules of protection and use of subsoil",
        allLi2870: "Illegal extraction of fish resources and other water animals and plants",
        allLi2880: "Illegal hunting",
        allLi2890: "Violation of rules of protection of animal life",
        allLi2900: "Illegal treatment with rare and endangered species of plants and animals (or) their parts and derivatives, as well as with plants and animals and (or) their parts and derivatives, the withdrawal of which is prohibited",
        allLi2910: "Illegal felling of trees and bushes",
        allLi2920: "Destruction or damaging of forests",
        allLi2930: "Violation of the regime of specially protected natural sites",
        allLi2940: "Failure to take measures on elimination of the consequences of environmental pollution",
        allLi2950: "Violation of traffic safety rules and the operation of railway, air or water transport",
        allLi2960: "Violation of traffic regulations and the operation of transport facilities by the persons who operate the transport facilities",
        allLi2970: "Leaving the place of road traffic accident",
        allLi2980: "The inferior repair of transport facilities and their release for service with technical faults, permission to operate the transport facility by a person in a state of intoxication",
        allLi2990: "Intentional disablement of transport vehicles or means of communication",
        allLi3000: "Violation of rules, ensuring the safe operation of transport",
        allLi3010: "Unauthorized unnecessarily train stop",
        allLi3020: "Violation of current rules on transport",
        allLi3030: "Violation of safety rules during the construction, operation or the repair of main pipelines",
        allLi3040: "Intentional damage or destruction of the pipeline",
        allLi3041: "Careless damage or destruction of pipelines",
        allLi3050: "Failure to render assistance to the suffering distress by captain of a ship",
        allLi3060: "Violation of rules of international flights",
        allLi3070: "Abuse of official authorities",
        allLi3071: "Illegal disclosure or other unlawful use of data and the information about operations with money and (or) other property",
        allLi3080: "Excess of powers or official authorities",
        allLi3090: "Assignment of powers of civil servant",
        allLi3100: "Illegal participation in the entrepreneurial activity",
        allLi3101: "Interfering with legal entrepreneurial activity",
        allLi3110: "Acceptance of a bribe",
        allLi3120: "Giving bribe",
        allLi3130: "Mediation in bribery",
        allLi3140: "Forgery by an official",
        allLi3150: "Inaction on service",
        allLi3160: "Negligence",
        allLi3170: "Desecration over the state symbols of the Republic of Kazakhstan",
        allLi3171: "Public insult and another infringement on the honor and dignity of the First President of the Republic of Kazakhstan-Leader of the Nation, profanation of portraits of the First President of the Republic of Kazakhstan - Leader of the Nation, obstruction of the legal activity of the First President Of the Republic of Kazakhstan - Leader of the Nation",
        allLi3172: "Violation of warranty of inviolability of the First President of the Republic of Kazakhstan – Leader of the Nation",
        allLi3180: "Infringement on the honor and dignity of the President of the Republic of Kazakhstan and the obstruction of his activity",
        allLi3190: "Infringement on the honor and dignity of the deputy and the obstruction of his activity",
        allLi3191: "Interfering with activity of the Constitutional Council of the Republic of Kazakhstan",
        allLi3200: "Insult of representative of authority",
        allLi3210: "Use of force in relation of representative of authority",
        allLi3211: "Interfering with activity of prosecutor and nonfulfillment of his (her) legal requirements",
        allLi3220: "Disclosure of information of security measures, which are used with regard to an office holder, who holds a senior public position",
        allLi3230: "Acquisition or sale of official documents and state awards",
        allLi3240: "Theft or damaging of documents, stamps, seals",
        allLi3250: "Forgery, production or sale of counterfeit documents, stamps, seals, blank forms, state awards",
        allLi3260: "Evasion of military service",
        allLi3270: "Arbitrariness",
        allLi3280: "Unwarranted appropriation of title of a representative of authority or an office holder, who holds a senior public position",
        allLi3290: "Illegal Rising of the State Flag",
        allLi3300: "Intentional illegal crossing of the State Border of the Republic of Kazakhstan",
        allLi3301: "Nonperformance of decision on deportation",
        allLi3302: "Organization of illegal migration",
        allLi3303: "Repeated violation of rules of involvement and use of foreign labor in the Republic of Kazakhstan",
        allLi3310: "Illegal change of the State border of the Republic of Kazakhstan.",
        allLi3320: "Illegal use of emblems and symbols of the Red Crescent and the Red Cross",
        allLi3330: "Violation of and failure to comply with the rules of communication lines security, and objects subject to state protection",
        allLi3340: "Violation of the procedure of organization and holding of meetings, rallies, pickets, street processions and demonstrations",
        allLi3350: "Conduct of a prohibited strike, obstruction of the work of enterprise, organization in the conditions of state of emergency",
        allLi3360: "Illegal interference of members of public associations in the activity of state bodies",
        allLi3370: "Creation or participation in the activity of illegal public and other associations",
        allLi3371: "Organization of the activities of a public or religious association or another organization following a court decision to prohibit their activities or to dissolve them on account of their incitement of extremism",
        allLi3380: "Rendering assistance to the political parties and trade unions of the foreign state",
        allLi3381: "Violation of the state of emergency regime",
        allLi3390: "Obstruction of the administration of public justice and the conduct of preliminary investigation",
        allLi3400: "Infringement on the life of a person, administering public justice or the preliminary investigation",
        allLi3410: "Threat or coercive actions on account of the administration of public justice or the conduct of preliminary investigation",
        allLi3420: "Contempt of a court",
        allLi3430: "Calumniation with regard to a judge, a juror, a public prosecutor, an investigator, a person who carries on an investigation, an expert member, an officer of justice, an officer of the court",
        allLi3440: "Involvement of certainly not guilty person to the criminal responsibility",
        allLi3450: "Certainly illegal release from criminal responsibility",
        allLi3460: "Knowingly illegal detention, placement in the detention or detention in the custody",
        allLi3470: "Compulsion of evidence",
        allLi3471: "excluded by the Law of the Republic of Kazakhstan dated 18.01.2011 No. 393-IV (the order of enforcement see Art.2)",
        allLi3480: "Falsification of evidences and operational and search materials",
        allLi3490: "Provocation of the corrupt business practices or corruption crime",
        allLi3500: "Imposition of certainly illegal sentence, decision or other judicial act",
        allLi3510: "Knowingly false denunciation",
        allLi3520: "Knowingly false testimony, conclusion of expert, specialist or erroneous translation",
        allLi3530: "Failure of the witness or injured person to give evidence",
        allLi3540: "Bribery or compulsion to give false evidences or evasion of giving evidences, false conclusion or to erroneous translation",
        allLi3550: "Disclosure of the investigation information or of the preliminary investigation",
        allLi3560: "Disclosure of details on safety measures, used in relation of persons, subject to the state protection",
        allLi3570: "Illegal action in relation of property, subjected to inventory or arrest or subject to confiscation",
        allLi3580: "Escape from the places of detention, arrest or custody",
        allLi3590: "Evasion from serving a sentence in the form of imprisonment",
        allLi3600: "Insubordination to the legal requirements of administration of criminal executive institution",
        allLi3610: "A threat of the use of force in relation of officer of institution, providing isolation from society, or his (her) relatives, as well as convicted person or infringement on their health or life",
        allLi3620: "Failure to comply with a court verdict, court decision or another judicial act",
        allLi3630: "Concealment of crime",
        allLi3631: "Hiding a crime",
        allLi3640: "Failure to report crime",
        allLi3650: "Interfering with legal activity of lawyers and other persons on protection of rights, freedoms and legal interests of person and citizen, as well as rendering of legal assistance to the individuals and legal entities",
        allLi3660: "Notion of a military crime",
        allLi3670: "Insubordination or other non-execution of order",
        allLi3680: "Resistance to the head or compulsion him (her) to violation of official obligations",
        allLi3690: "Violent actions in relation of the head",
        allLi3700: "Violation of charter rules of relationship between military servants in the absence between them subordination relations",
        allLi3710: "Criminal insult of a military servant",
        allLi3720: "Unwarranted leaving of unit or place of service",
        allLi3730: "Desertion",
        allLi3740: "Evasion of military service by means of self-injury or by another method",
        allLi3750: "Evasion or refusal of serving military service",
        allLi3760: "Violation of rules of frontier guard duty",
        allLi3770: "Violation of charter rules of serving of guard (watch keeping) service",
        allLi3780: "Violation of charter rules of serving of internal service or patrol in the garrison",
        allLi3790: "Violation of rules of serving of service on protection of public order and ensuring of public security",
        allLi3800: "Abuse of authority",
        allLi3801: "Exceeding authority",
        allLi3802: "Failure to use authority",
        allLi3810: "Habitual negligence in office",
        allLi3820: "Abandonment of a warship in distress",
        allLi3830: "Surrender or leaving of means of warfare to the enemy",
        allLi3840: "Voluntary surrender into captivity",
        allLi3850: "Looting",
        allLi3860: "Disclosure of security information of military kind or loss of documents, containing security information of military kind",
        allLi3870: "Intentional destruction or damaging of military property",
        allLi3880: "Negligent destruction or damaging of military property",
        allLi3890: "Loss of military property",
        allLi3900: "Violation of rules of weapon handling and also substances and items, posing a danger for the wider public",
        allLi3910: "Violation of rules of driving or operating of vehicles",
        allLi3920: "Violation of flight rules or training to them",
        allLi3930: "Violation of rules of ship navigation"
    },
    kk: true,
    ru: true
});

