define({
    root: {
        title: "Map of criminal violations",
        back: "Other Committee GIS",
        aLocale: "Languages",
        aExternal0: "Local police stations",
        aExternal1: "Apply to police",
        aExternal2: "Verify your application to police…",
        aExternal3: "Apply to prosecution authorities",
        aShare: "Share",
        lblPeriod: "Period:&#160;",
        lblFilter: "Filter:&#160;",
        apply: "Show",
        hideStatistic: "Clean",
        aAddress: "ADDRESSES",
        aPeriod: "PERIOD",
        aFilter: "FILTER",
        aView: "VIEW",
        aTable: "STATISTICS",
        aType: "MAPS",
        aMail: "SUBSCRIBING",
        aAbout: "ABOUT",
        aFeedBack: "OPINION",
        aPrint: "PRINT",
        closeParams: "x close",
        pnPeriod: "Period",
        notePeriod: "Specify a period for which you would like to see the data",
        lblPeriodDay: "Per a day",
        lblPeriodMonth: "From the beginning of the month",
        lblPeriodYear: "From the beginning of the year",
        applyPeriod: "Apply",
        pnLaw: "Filter",
        noteLaw: "Set filter on the interested types of offences",
        applyFilter: "Apply",
        pnView: "View",
        noteView: "Specify level of statistics.",
        lblLvlArea: "regions",
        lblLvlRegion: "districts",
        lblLvlCity: "cities",
        noteData: "Specify the method of data presentation.",
        lblViewPoint: "points",
        lblViewHeat: "heat map",
        noteViewHeat: "*city-wide only",
        applyView: "Apply",
        pnAddress: "Address search",
        lblParObl: "Region",
        lblPL: "Populated locality",
        bringCloser: "Zoom",
        pnMap: "Base map",
        noteMap: "Choose map",
        lblTileMap: "Map of CLS&SR",
        lblOsmMap: "People’s map",
        noteMap1: "* Base map is the basis of map, statistical information will be displayed on its background.",
        pnPrint: "Print",
        notePrintFile: "Specify file format to which map export will be implemented",
        notePrint: "Press \"Print\" and wait for the link to the file is generated as a \"Result\", which then you can save and print",
        btnPrint: "Print",
        btnRef: "Result",
        lblErrMsg: "Error:&#160;",
        pnDelivery: "Subscribing",
        noteDelivery: "Subscribe to \"Data on offenses committed in your region\"",
        lblXY: "Coordinates of the center of the interested region:",
        noteXY: "*Click on map where you need",
        lblEmail: "Your е-mail:",
        inptEmailPH: "Specify your e-mail address...", //placeholder
        lblRadius: "Pickup range from the specified center (from 1000m to 4000m):",
        inptRadiusIM: "Value shall be with figures!", //invalidMessage
        lblMailPeriod: "Statistics submission period:",
        subscribe: "Subscribe",
        btnFullSize: "Whole map",
        btnZoomIn: "Zoom",
        btnZoomOut: "Pinch",
        btnLocation: "My location",
        btnOverviewMap: "View map",
        infoMarker: "Additional information",
        msgInvalidDate: "Invalid date!",
        msgLawUndefined: "Articles not selected!",
        msgLocalityUnable: "Impossible to define a location",
        msgLocalityNotAvailable: "Current location unavailable",
        msgLocalityTimeout: "Time is up",
        msgLocalityUnknown: "Unknown mistake",
        msgLocalityOldBrowser: "Your browser does not maintain location determination. You can find a list of supported browsers at http://caniuse.com.",
        infoTextTitle1: "Total found:",
        infoTextCol1: "Clause",
        infoTextCol2: "Region",
        infoTextCol3: "Number&#9660;",
        infoTextTitle2: "Total",
        infoTextTitle3: "from the beginning of the year:",
        infoWinTitle: "Detailed information",
        infoWinColNum: "№: ",
        infoWinColOrg: "State authority: ",
        infoWinColDate: "Date of updating: ",
        infoWinColDateFulfillment: "Date: ",
        infoWinColLaw: "Article: ",
        infoWinColHard: "Degree: ",
        infoWinColStreet: "Street: ",
        infoWinColHouse: "Building: ",
        infoWinColPlace: "Crime scene: ",
        infoWinChartDate: "as on ",
        infoWinRegColK: "Number of criminal violations: ",
        infoWinRegColK10: "Number on 10 thousand people: ",
        msgRegionUndefined: "Specify a region!",
        templateTitle: "Map of criminal violations",
        templateAuthor: "© CLS&SR",
        msgCoordinatesUndefined: "Position is not specified!",
        msgRadiusInvalid: "Invalid range format!",
        msgRadiusInvalid1: "The range of the radius must be between 1000 m and 4000 m!",
        msgEMailInvalid: "Invalid e-mail format!",
        msgDeliveryOK: "You have successfully signed up for a newsletter. To confirm a newsletter you are sent an activation letter to your e-mail.",
        msgErrQuery: "Request error",
        errValNotFound: "Data not found",
        statusViewArea: "regions",
        statusViewRegion: "districts",
        statusViewCrime: "criminal violations",
        legendMore: " and more",

        mapCrime: 'Map of criminal violations',

        mapUa: 'Map of criminal offenses committed by minors',
        mapRta: 'Map of accidents',
        mapOl: 'Map of application by individuals and legal persons to public bodies',

        mapNarcotic: 'Narcocrimes',
        mapJa: 'Debtors for enforcement proceedings',
        mapP: 'Map of persons who have committed sexual assault against minors',

        lawUndefined: "Article is not defined",

        hardAverage: "average",
        hardGrave: "heavy",
        hardStrong: "gravest",
        hardSmall: "minor",

        titleHard0: "criminal violations",
        titleHard1: "criminal violations  of little gravity",
        titleHard2: "criminal violations  of average-gravity",
        titleHard3: "grave criminal violations",
        titleHard4: "gravest criminal violations",
        titleHard5: "criminal offences",
        titleHard6: "criminal infractions",

        btnCancel: "Cancel",
        titleAddress: "Address",
        lblHouse: "House number",
        lblGeonim: "District/Street",
        placeholderFilter: "Enter the name, press <Enter>",
        lblTime: "Time of the crime: ",
        regionRK: "Republic of Kazakhstan",
        lblName: "Name",
        lblDescription: "Description",

        msgDateEndLess: "Дата начала периода не может быть позже даты окончания!",
        msgPeriodMore366: "Нужно уменьшить период запроса до 366 дней!",
        msgPeriodMore31: "Нужно уменьшить период запроса до 31 дня!",
        msgValNotSelect: "Значение не выбрано!",
        msgValNotFound: "Значения не найдены",
        msgRequestFailed: "Ошибка запроса",
        msgEnterValue: "Введите значение!",
        msgCoordNotDefined: "Координаты для зданий не определены",
        msgSetLowerLevel: "Выберите значение уровнем ниже!",
        aMVD: "Подробнее на сайте МВД",
        mapTitle0: "CLS&SR",
        mapTitle1: "Streets",
        mapTitle2: "Imagery",
        mapTitle3: "Topo",
        mapTitle4: "Google map",
        mapTitle5: "Google satellite",
        mapTitle6: "Google mixed",
        msgSlideNotAvailable: 'Режим "Слайды" доступен только в масштабе города',
        lblTimeSlider: 'en Режим "Time Slider"',
        noteTimeSlider0: "en Режим обеспечивает последовательное отображение данных об уголовных правонарушениях на каждую дату ",
        noteTimeSlider1: "en из определенного интервала времени",
        noteTimeSlider2: "en с установленными фильтрами ",
        noteTimeSlider3: "en *Заданный интервал не может превышать 31 день. Режим доступен только в масштабе города. До выхода из режима навигация по карте и другие функции будут не доступны.",
        btnTimeSlider: "Activate",
        btnSliderShow: "en Начать показ",
        btnPrevSlide: "en Предыдущий слайд",
        btnNextSlide: "en Следующий слайд",
        btnSliderExit: "en Выход из режима",
        lblIncreasingly: "en с нарастанием",
        lblPolice: "local police stations",
        lblPeriodManual: "Manual",
        aRULE: "МАРШРУТ",
        pnRule: "en Маршрут",
        lblDistance: "en Расстояние:",
        noteRoute: "en *Щёлкните по карте на нужном месте, чтобы обозначить отправную точку вашего маршрута. Нарисуйте путь, щелкая по карте на каждом из пунктов маршрута.",
        distanceSegment: "en Отрезок ",
        metricKM: "км"
    },
    kk: true,
    ru: true
});
