define({
    title: "Карта уголовных правонарушений",
    back: "Другие ГИС Комитета",
    aLocale: "Выбор языка",
    aExternal0: "Участковые пункты полиции",
    aExternal1: "Подать заявление в полицию",
    aExternal2: "Проверить свое заявление в полицию…",
    aExternal3: "Подать заявление в органы прокуратуры",
    aShare: "Поделиться",
    lblPeriod: "Период:&#160;",
    lblFilter: "Фильтр:&#160;",
    apply: "Показать",
    hideStatistic: "Очистить",
    aAddress: "АДРЕСА",
    aPeriod: "ПЕРИОД",
    aFilter: "ФИЛЬТР",
    aView: "ВИД",
    aTable: "СТАТИСТИКА",
    aType: "КАРТЫ",
    aMail: "ПОДПИСКА",
    aAbout: "О ПРОЕКТЕ",
    aFeedBack: "ОТЗЫВЫ",
    aPrint: "ПЕЧАТЬ",
    closeParams: "x закрыть",
    pnPeriod: "Период",
    notePeriod: "Укажите период, за который Вы бы хотели видеть данные",
    lblPeriodDay: "За сутки",
    lblPeriodMonth: "C начала месяца",
    lblPeriodYear: "C начала года",
    applyPeriod: "Применить",
    pnLaw: "Фильтр",
    noteLaw: "Установите фильтр по интересуемым Вас видам правонарушений",
    applyFilter: "Применить",
    pnView: "Вид",
    noteView: "Укажите уровень статистики.",
    lblLvlArea: "области",
    lblLvlRegion: "районы",
    lblLvlCity: "города",
    noteData: "Укажите способ отображения данных.",
    lblViewPoint: "точки",
    lblViewHeat: "тепловая карта",
    noteViewHeat: "*только в масштабе города",
    applyView: "Применить",
    pnAddress: "Адресный поиск",
    lblParObl: "Область",
    lblPL: "Населенный пункт",
    bringCloser: "Приблизить",
    pnMap: "Базовая карта",
    noteMap: "Выберите карту",
    lblTileMap: "Карта КПСиСУ",
    lblOsmMap: "Народная карта",
    noteMap1: "* Базовая карта является основой карты, на ее фоне отображается статистическая информация.",
    pnPrint: "Печать",
    notePrintFile: "Укажите формат файла, в который будет осуществлен экспорт карты",
    notePrint: "Нажмите кнопку \"Печать\" и дождитесь пока будет сформирована ссылка в виде кнопки \"Результат\" на файл, который вы сможете сохранить и распечатать",
    btnPrint: "Печать",
    btnRef: "Результат",
    lblErrMsg: "Ошибка:&#160;",
    pnDelivery: "Подписка",
    noteDelivery: "Подпишитесь на рассылку \"Сведения о совершенных правонарушениях в Вашем районе\"",
    lblXY: "Координаты центра интересуемого Вас района:",
    noteXY: "*Щёлкните по карте на нужном месте",
    lblEmail: "Ваш е-mail:",
    inptEmailPH: "Укажите адрес Вашей эл. почты...", //placeholder
    lblRadius: "Радиус охвата от указанного центра (от 1000 до 4000 м.):",
    inptRadiusIM: "Значение должно состоять из цифр!", //invalidMessage
    lblMailPeriod: "Период предоставления статистики:",
    subscribe: "Подписаться",
    btnFullSize: "Вся карта",
    btnZoomIn: "Увеличить",
    btnZoomOut: "Уменьшить",
    btnLocation: "Моё местоположение",
    btnOverviewMap: "Обзорная карта",
    infoMarker: "Дополнительная информация",
    msgInvalidDate: "Неверное значение даты!",
    msgLawUndefined: "Статьи не выбраны!",
    msgLocalityUnable: "Невозможно определить местоположение",
    msgLocalityNotAvailable: "Текущее положение недоступно",
    msgLocalityTimeout: "Время истекло",
    msgLocalityUnknown: "Неизвестная ошибка",
    msgLocalityOldBrowser: "Ваш браузер не поддерживает определение местонахождения. По адресу http://caniuse.com можно найти список поддерживаемых браузеров.",
    infoTextTitle1: "Всего найдено:",
    infoTextCol1: "Статья",
    infoTextCol2: "Регион",
    infoTextCol3: "Кол-во&#9660;",
    infoTextTitle2: "Всего",
    infoTextTitle3: "с начала года:",
    infoWinTitle: "Детальная информация",
    infoWinColNum: "№ КУИ: ",
    infoWinColOrg: "Гос.орган: ",
    infoWinColDate: "Дата возб.: ",
    //infoWinColDateFulfillment: "Дата совер.: ",
    infoWinColDateFulfillment: "Дата возбужд. УД: ",
    infoWinColLaw: "Статья: ",
    infoWinColHard: "Тяжесть: ",
    infoWinColStreet: "Улица: ",
    infoWinColHouse: "Дом: ",
    infoWinColPlace: "Место совершения: ",
    infoWinChartDate: "на ",
    infoWinRegColK: "Кол-во уголовных правонарушений: ",
    infoWinRegColK10: "Кол-во на 10 тыс. человек: ",
    msgRegionUndefined: "Укажите регион!",
    templateTitle: "Карта уголовных правонарушений",
    templateAuthor: "© КПСиСУ",
    msgCoordinatesUndefined: "Не указаны координаты!",
    msgRadiusInvalid: "Не верный формат радиуса!",
    msgRadiusInvalid1: "Диапазон радиуса должен быть от 1000 до 4000 м.!",
    msgEMailInvalid: "Неверный формат e-mail!",
    msgDeliveryOK: "Вы успешно подписались на рассылку. Для подтверждения подписки, Вам на почту отправлено письмо активации",
    msgErrQuery: "Ошибка запроса",
    errValNotFound: "Значения не найдены",
    statusViewArea: "области",
    statusViewRegion: "районы",
    statusViewCrime: "уголовных правонарушений",
    legendMore: " и более",
    mapCrime: 'Карта уголовных правонарушений',
    mapUa: 'Карта уголовных правонарушений несовершеннолетних',
    mapRta: 'Карта аварийности',
    mapOl: 'Карта обращений лиц',
    mapNarcotic: 'Наркопреступления',
    mapJa: 'Должники по исполнительным производствам',
    mapP: 'Карта лиц, совершивших насильственные действия сексуального характера в отношении несовершеннолетних',
    lawUndefined: "Статья не определена",
    hardAverage: "средняя",
    hardGrave: "тяжкое",
    hardStrong: "особо тяжкое",
    hardSmall: "небольшая",
    titleHard0: "уголовных правонарушений",
    titleHard1: "уголовных правонарушений небольшой тяжести",
    titleHard2: "уголовных правонарушений средней тяжести",
    titleHard3: "тяжких уголовных правонарушений",
    titleHard4: "особо тяжких уголовных правонарушений",
    titleHard5: "уголовных преступлений",
    titleHard6: "уголовных проступков",
    btnCancel: "Отмена",
    titleAddress: "Адрес",
    lblHouse: "Номер дома",
    lblGeonim: "Микрорайон/улица",
    placeholderFilter: "Введите название, нажмите <Enter>",
    lblTime: "Время совершения преступления: ",
    regionRK: "Республика Казахстан",
    lblName: "Наименование",

    msgDateEndLess: "Дата начала периода не может быть позже даты окончания!",
    msgPeriodMore366: "Нужно уменьшить период запроса до 366 дней!",
    msgPeriodMore31: "Нужно уменьшить период запроса до 31 дня!",
    msgValNotSelect: "Значение не выбрано!",
    msgValNotFound: "Значения не найдены",
    msgRequestFailed: "Ошибка запроса",
    msgEnterValue: "Введите значение!",
    msgCoordNotDefined: "Координаты для зданий не определены",
    aMVD: "Подробнее на сайте МВД",
    lblDescription: "Описание",
    mapTitle0: "КПСиСУ",
    mapTitle1: "Улицы",
    mapTitle2: "Снимки",
    mapTitle3: "Топогра-фическая",
    mapTitle4: "Google карта",
    mapTitle5: "Google спутник",
    mapTitle6: "Google смешанный",
    msgSlideNotAvailable: 'Режим "Слайды" доступен только в масштабе города',
    lblTimeSlider: 'Режим "Time Slider"',
    noteTimeSlider0: "Режим обеспечивает последовательное отображение данных об уголовных правонарушениях на каждую дату ",
    noteTimeSlider1: "из определенного интервала времени",
    noteTimeSlider2: "с установленными фильтрами ",
    noteTimeSlider3: "*Заданный интервал не может превышать 31 день. Режим доступен только в масштабе города. До выхода из режима навигация по карте и другие функции будут не доступны.",
    btnTimeSlider: "Включить",
    btnSliderShow: "Начать показ",
    btnPrevSlide: "Предыдущий слайд",
    btnNextSlide: "Следующий слайд",
    btnSliderExit: "Выход из режима",
    lblIncreasingly: "с нарастанием",
    lblPolice: "участковые пункты полиции",
    lblPeriodManual: "Произвольный",
    aRULE: "МАРШРУТ",
    pnRule: "Маршрут",
    lblDistance: "Расстояние:",
    noteRoute: "*Щёлкните по карте на нужном месте, чтобы обозначить отправную точку вашего маршрута. Нарисуйте путь, щелкая по карте на каждом из пунктов маршрута.",
    distanceSegment: "Отрезок ",
    metricKM: "км"
});
