define({
    title: "Қылмыстық құқық бұзушылықтар картасы",
    back: "Комитеттің басқа ГАЖ",
    aLocale: "Тіл",
    aExternal0: "Учаскелік полициялық пункттері",
    aExternal1: "Полицияға өтініш беру",
    aExternal2: "Полицияға берген өз өтінішімді тексеру…",
    aExternal3: "Прокуратура органдарына өтініш беру",
    aShare: "Бөлісу",
    lblPeriod: "Кезең:&#160;",
    lblFilter: "Сүзгі:&#160;",
    apply: "Көрсету",
    hideStatistic: "Тазарту",
    aAddress: "МЕКЕНЖАЙ",
    aPeriod: "КЕЗЕҢ",
    aFilter: "СҮЗГІ",
    aView: "ТҮР",
    aTable: "СТАТИСТИКА",
    aType: "КАРТАЛАР",
    aMail: "ЖАЗЫЛУ",
    aAbout: "ЖОБА ТУРАЛЫ",
    aFeedBack: "ПІКІРЛЕР",
    aPrint: "Басып шығару",
    closeParams: "x жабу",
    pnPeriod: "Кезең",
    notePeriod: "Сіз деректерді көргіңіз келетін кезеңді көрсетіңіз",
    lblPeriodDay: "Тәулікке",
    lblPeriodMonth: "Айдың басынан бастап",
    lblPeriodYear: "Жылдың басынан бастап",
    applyPeriod: "Қолдану",
    pnLaw: "Сүзгі",
    noteLaw: "Сіз іздеген құқық бұзушылықтар бойынша сүзгі орнатыңыз",
    applyFilter: "Қолдану",
    pnView: "Түрі",
    noteView: "Статистика деңгейін таңдаңыз.",
    lblLvlArea: "облыстар",
    lblLvlRegion: "аудандар",
    lblLvlCity: "қалалар",
    noteData: "Деректердің бейнелену тәсілін таңдаңыз.",
    lblViewPoint: "нүктелер",
    lblViewHeat: "жылулық карта",
    noteViewHeat: "*тек қала масштабында",
    applyView: "Қолдану",
    pnAddress: "Мекенжай іздеу",
    lblParObl: "Облыс",
    lblPL: "Елді мекені",
    bringCloser: "Жақындату",
    pnMap: "Базалық карта",
    noteMap: "Картаны таңдаңыз",
    lblTileMap: "ҚСжАЕК картасы",
    lblOsmMap: "Халық картасы",
    noteMap1: "* Базалық карта негізгі карта болып табылады, оның аясында статистикалық ақпарат бейнеленеді.",
    pnPrint: "Басып шығару",
    notePrintFile: "Картаның экспорты жүзеге асырылатын файлдың форматын көрсетіңіз",
    notePrint: "\"Басып шығару\" батырмасын басыңыз және сіз сақтай және басып шығара алатын файлға \"Нәтиже\" батырмасы түрінде сілтеме қалыптасқанға дейін күтіңіз",
    btnPrint: "Басып шығару",
    btnRef: "Нәтиже",
    lblErrMsg: "Қате:&#160;",
    pnDelivery: "Жазылу",
    noteDelivery: "\"Сіздің ауданыңызда жасалған құқық бұзушылықтар туралы мәліметтер\" жіберіліміне жазылыңыз",
    lblXY: "Сіз іздеген аудан орталығының координаттары:",
    noteXY: "*Керек жерде картаға басыңыз",
    lblEmail: "Сіздің е-mail:",
    inptEmailPH: "Сіздің эл.пошта мекенжайыңызды көрсетіңіз...", //placeholder
    lblRadius: "Көрсетілген орталықтан қамту радиусы (1000-нан 4000 м-ге дейін):",
    inptRadiusIM: "Мән сандардан құралуы тиіс!", //invalidMessage
    lblMailPeriod: "Статистиканы ұсыну кезеңі:",
    subscribe: "Жазылу",
    btnFullSize: "Бүкіл карта",
    btnZoomIn: "Ұлғайту",
    btnZoomOut: "Кішірейту",
    btnLocation: "Менің орналасқан жерім",
    btnOverviewMap: "Бақылау картасы",
    infoMarker: "Қосымша ақпарат",
    msgInvalidDate: "Күні дұрыс қойылмаған!!",
    msgLawUndefined: "Баптар таңдалмаған!",
    msgLocalityUnable: "Орналасқан жерін анықтау мүмкін емес",
    msgLocalityNotAvailable: "Ағымдағы күйі қолжетімсіз",
    msgLocalityTimeout: "Уақыт аяқталды",
    msgLocalityUnknown: "Белгісіз қате",
    msgLocalityOldBrowser: " Сіздің браузеріңіз орналасқан жерін анықтауды қолдамайды. http://caniuse.com мекенжайы бойынша қолдау көрсетілетін браузерлердің тізімін табуға болады.",
    infoTextTitle1: "Барлығы табылды:",
    infoTextCol1: "Бап",
    infoTextCol2: "Өңірі",
    infoTextCol3: "Саны&#9660;",
    infoTextTitle2: "Жыл басынан бері",
    infoTextTitle3: "барлығы:",
    infoWinTitle: "Толық ақпарат",
    infoWinColNum: "№ АЕАК: ",
    infoWinColOrg: "Мемлекеттік орган: ",
    infoWinColDate: "Қозғау күні: ",
    infoWinColLaw: "Бабы: ",
    infoWinColHard: "Ауырлығы: ",
    infoWinColStreet: "Көшесі: ",
    infoWinColHouse: "Үйі: ",
    infoWinColPlace: "Место совершения: ",
    infoWinChartDate: " ",
    infoWinRegColK: "Қылмыстық құқық бұзушылықтар саны: ",
    infoWinRegColK10: "10 мың адамға шаққандағы саны: ",
    msgRegionUndefined: "Құрметті өңір!",
    templateTitle: "Қылмыстық құқық бұзушылықтар картасы",
    templateAuthor: "© ҚСжАЕК",
    msgCoordinatesUndefined: "Координаттар көрсетілмеген!",
    msgRadiusInvalid: "Радиус форматы қате!",
    msgRadiusInvalid1: "Радиус диапазоны 1000-нан бастап 4000 м-ге дейін болуы тиіс!",
    msgEMailInvalid: "Е-mail форматы қате!",
    msgDeliveryOK: "Сіз таралымға сәтті жазылдыңыз. Таралымды растау үшін, Сіздің поштаңызға іске қосу хаты жолданды",
    msgErrQuery: "Сұрау қатесі",
    errValNotFound: "Мәндер табылмады",
    statusViewArea: "облыстар",
    statusViewRegion: "аудандар",
    statusViewCrime: "қылмыстық құқық бұзушылықтар",
    legendMore: "және астам",
    mapCrime: 'Қылмыстық құқық бұзушылықтар картасы',
    mapUa: 'Кәмелетке толмағандар жасаған қылмыстық құқық бұзушылықтар картасы',
    mapRta: 'Апаттылық картасы',
    mapOl: 'Жеке және заңды тұлғалардың мемлекеттік органдарға жүгінулерінің картасы',
    mapNarcotic: 'Наркопреступления',
    mapJa: 'Должники по исполнительным производствам',
    mapP: 'Кәмелетке толмағандарға қатысты сексуалдық сипаттағы зорлық әрекеттерін жасаған адамдардың картасы',
    lawUndefined: "Бап анықталған жоқ",
    hardAverage: "орташа",
    hardGrave: "ауыр",
    hardStrong: "аса ауыр",
    hardSmall: "жеңіл",
    titleHard0: "қылмыстық құқық бұзушылықтар",
    titleHard1: "ауырлығы жеңіл қылмыстық құқық бұзушылықтар",
    titleHard2: "ауырлығы орташа қылмыстық құқық бұзушылықтар",
    titleHard3: "ауыр қылмыстық құқық бұзушылықтар",
    titleHard4: "ауа ауыр қылмыстық құқық бұзушылықтар",
    titleHard5: "қылмыстық іс",
    titleHard6: "қылмыстық теріс қылықтар",
    btnCancel: "Жою",
    titleAddress: "Мекенжай",
    lblHouse: "Үй нөмірі",
    lblGeonim: "Ықшам ауданы/көшесі",
    regionRK: "Қазақстан Республикасы",
    lblName: "Атауы",

    infoWinColDateFulfillment: "Дата возбужд. УД: ",
    lblTime: "Время совершения преступления: ",
    placeholderFilter: "Введите название, нажмите <Enter>",
    msgDateEndLess: "Дата начала периода не может быть позже даты окончания!",
    msgPeriodMore366: "Нужно уменьшить период запроса до 366 дней!",
    msgPeriodMore31: "Нужно уменьшить период запроса до 31 дня!",
    msgValNotSelect: "Значение не выбрано!",
    msgValNotFound: "Значения не найдены",
    msgRequestFailed: "Ошибка запроса",
    msgEnterValue: "Введите значение!",
    msgCoordNotDefined: "Координаты для зданий не определены",
    aMVD: "Подробнее на сайте МВД",
    lblDescription: "Описание",
    mapTitle0: "ҚСжАЕК",
    mapTitle1: "Улицы",
    mapTitle2: "Снимки",
    mapTitle3: "Топогра-фическая",
    mapTitle4: "Google карта",
    mapTitle5: "Google спутник",
    mapTitle6: "Google смешанный",
    msgSlideNotAvailable: 'Режим "Слайды" доступен только в масштабе города',
    lblTimeSlider: 'Режим "Time Slider"',
    noteTimeSlider0: "Режим обеспечивает последовательное отображение данных об уголовных правонарушениях на каждую дату ",
    noteTimeSlider1: "из определенного интервала времени",
    noteTimeSlider2: "с установленными фильтрами ",
    noteTimeSlider3: "*Заданный интервал не может превышать 31 день. Режим доступен только в масштабе города. До выхода из режима навигация по карте и другие функции будут не доступны.",
    btnTimeSlider: "Включить",
    btnSliderShow: "Начать показ",
    btnPrevSlide: "Предыдущий слайд",
    btnNextSlide: "Следующий слайд",
    btnSliderExit: "Выход из режима",
    lblIncreasingly: "с нарастанием",
    lblPolice: "учаскелік полициялық пункттері",
    lblPeriodManual: "Произвольный",
    aRULE: "МАРШРУТ",
    pnRule: "Маршрут",
    lblDistance: "Расстояние:",
    noteRoute: "*Щёлкните по карте на нужном месте, чтобы обозначить отправную точку вашего маршрута. Нарисуйте путь, щелкая по карте на каждом из пунктов маршрута.",
    distanceSegment: "Отрезок ",
    metricKM: "км"
});
